# It is recommended to specify the latest version of Python
# supported by your project here, or alternatively use
# pre-commit's default_language_version, see
# https://pre-commit.com/#top_level-default_language_version

default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.5.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables            
          - --remove-all-unused-imports

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: 
          - --line-length=79
          - --profile=black

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - --line-length=79
          - --include='\.pyi?$'
          - --exclude="""\.git |
                         \.__pycache__|
                         \.hg|
                         \.mypy_cache|
                         \.tox|
                         \.venv|
                         _build|
                         buck-out|
                         build|
                         dist"""